### ISSUE TITLE
Why is Postgres a requirement?

### ISSUE THREAD

**Issue by venomone** [rremizov/django-random-queryset#72]
Hello,

nice library :D but i would like to use it against my MySQL /Galera cluster. Why is postgres a requirment as you have writtin at the README.me?

Kind regards

**Comment by rremizov** [comment]
Hey! Thanks for the interest in this project!

MySQL is not in the readme mostly because I don't have much experience using it. Django provides an abstraction layer around databases, and this library doesn't use any Postgres-specific features of Django. Therefore, you should be fine using it with MySQL, but I can't say for sure.

Before using it with MySQL, I would check the following:
1. Currently, the tests are run by Travis against Postgres only. Running them against MySQL should help to catch possible minor bugs (if there are any).
2. The SQL queries this library generates may prove to be suboptimal for MySQL. Therefore some testing should be done if you expect to use this library against a large table (think hundreds of thousands of rows).

**Comment by venomone** [comment]
I can also confirm that you library is working with MariaDB/mySQL.
Thanks for your feedback
